# HW 7 - Libraries + Modules
ULAB - Physics and Astronomy Division \
Due **Wednesday, November 6th, 2024 at 11:59pm** on Gradescope

--------------------------------------------------------------

## Module vs. Package vs. Library
### Module
A **module** is a single file containing Python code (typically ending in a `.py` extension) that contains functions and variables. 
- They can be imported into other Python files or notebooks
- You use modules to organize code into smaller, reuseable parts
- Ex: `even_sum.py` that we created during lecture.

*You will create your OWN module for this homework and use that we made during class.*

### Package
A **package** is a group of modules, organized like a directory. 
- A package requires a special `__init__.py` file to tell Python that the ENTIRE directory is something you would like to import.
- Packages can contain sub-pacakges
- Ex: `BAGLE_Microlensing` is an example of a package (if you are in Dex's group, this should be familar to you). Or you could think of `paarti` if you are in Brianna's group.

*You will NOT be working with a package for this homework.*

### Library
A **library** is a much broader term that also refers to a collection of modules (like a package) but a library can also contain mulitple packages. 
- Libraries serve a much wider range of functionality for
- Programmers use packages to have ready-to-go tools that can be used for data manipulation, web development, machine learning or simulations.
- Ex: `numpy` is a very common library. Later in this course we will also be working some of the following libraries `matplotlib`, `scipy`, and `astropy`, `pandas`, etc

*You WILL be working with the extensive numpy library for this homework!*

--------------------------------------------------------------

# 1 NumPy
**NumPy** (aka Numerical Python) is a library that was designed for caring out computations in Python. 

We did not have a ton of time to work through examples during class, so I will ask that you check out this website for more information: https://numpy.org/doc/ 

Before we can work through any problems, you need to call the following in your notebook:

In [7]:
import numpy as np

## 1.1 Lists vs. Arrays
*When I first started working with NumPy I didn't understand what was so special about arrays. This homework problem should help illustrate the difference. Make sure to follow each step and follow good coding practices.*

1) Make a list called `my_list` and make an array called `my_arr` with the same values. There is an example below, but don't copy mine! Ex:
```
my_list = [11, 12, 13, 14, 15]
my_arr = np.array([11, 12, 13, 14, 15])
```
*Notice that to use the `numpy` package we had to call its short cut `np` and then call upon its funciton `.array()`. This is similar to working with a built-in python function like `.append()`.*

In [8]:
# Your code here
my_list = [10, 12, 14, 16, 18]
my_arr = np.array([15, 20, 25, 30, 35])

2) Multiply `my_list` by 4 and multiply `my_arr` by 4. Print the results. Describe what happens in a comment.

In [9]:
# Your code here
print(my_list * 4)
print(my_arr * 4)

[10, 12, 14, 16, 18, 10, 12, 14, 16, 18, 10, 12, 14, 16, 18, 10, 12, 14, 16, 18]
[ 60  80 100 120 140]


In [ ]:
# Muliplying my_list by 4, essentially repeats the list 4 times, however multiplying the array by 4 multiplies each of the entries by 4

3) Add `my_list` with `my_list`. Add `my_arr` with `my_arr`. Add `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [10]:
# Your code here
print(my_list + my_list)
print(my_arr + my_arr)
print(my_list + my_arr)

[10, 12, 14, 16, 18, 10, 12, 14, 16, 18]
[30 40 50 60 70]
[25 32 39 46 53]


In [ ]:
# adding the two lists repeats them, adding the list with the array adds the entries, just like adding the two arrays does.

4) Subtract `my_list` with `my_list`. Subtract `my_arr` with `my_arr`. Subtract `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [22]:
# Your code here
# print(my_list - my_list)
print(my_arr - my_arr)
print(my_list - my_arr)

[0 0 0 0 0]
[ -5  -8 -11 -14 -17]


In [ ]:
# You get an error because you can't subtract lists but you can subtract arrays and they subtract just like the arrays add

5) Multiply `my_list` with `my_list`. Multply `my_arr` with `my_arr`. Multiply `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [21]:
# Your code here
# print(my_list * my_list)
print(my_arr * my_arr)
print(my_arr * my_list)

[ 225  400  625  900 1225]
[150 240 350 480 630]


In [ ]:
# You can't multiply lists, but when you multiply the two arrays, it squares each of the entries. 
# When you multiply the list by the array it multiplies each of the entries in the array by the corresponding entry in the list

7) Divide `my_list` with `my_list`. Divide `my_arr` with `my_arr`. Divide `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [23]:
# Your code here
# print(my_list / my_list)
print(my_arr / my_arr)
print(my_arr / my_list)

[1. 1. 1. 1. 1.]
[1.5        1.66666667 1.78571429 1.875      1.94444444]


In [ ]:
# Similarly, you cant divide two lists. When you divide the array by the array, it divides each of the entrys by itself, producing 1. 
# When you divide the array by the list, it does standard division (arr entry 1 / list entry 1) so on and so forth, rounding after the 8th decimal

8) After working through this problem, in at least two sentences, describe the difference between a list and an array.

In [24]:
# Your code here
# Lists can store all different types of data (integers, strings etc.) while arrays can only store values of floats or integers. Also all the data in an array has to be of the same type. 
# Arrays can be used with numpy to do calculations, with other arrays while lists cannot be used to do high level calculations.

## 1.2 Nested List and Multi-Dimensional Arrays
A **nested list** is when you have a list as an element for a list. Example:
```
nested_list = [[1, 2, 3], [4, 5, 6]]
```

A **multi-dimensional array** is essentially a nested list, but it contains the properties of a matrix. Example:
```
multi_d_array = np.array([[1, 2, 3], [4, 5, 6]])
```

Go to this website for more information on NumPy: https://www.w3schools.com/python/numpy/default.asp

Write a **function** that takes in a two-dimensional array. Example:

```
arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
```

and then returns the second value in each row. Example:

```
[4, 10, 16]
```

In [3]:
# Your code here
import numpy as np

def get_second_values(arr):
    # Assuming arr is a 2D NumPy array, return the second values in every array
    return arr[:, 1]

arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
result = get_second_values(arr3)
print(result)

[ 4 10 16]


In 2-3 sentences, describe what section of the website helped you write your function. 

In [4]:
# Your comment here
# The NumPy section on slicing and indexing was really helpful while I was writing this function. 
# It helped a lot while I was trying to figure out  how to access specific elements in an array using the syntax arr[:, 1] 
# This call arr[:, 1] allows us to select all rows and a specific column. 
# This call made it really straightforward to call the second value from each row without a lot of crazy confusing coding.

How would you take a nested list and return the second value in each row? Explain in 2-3 sentences and show an example.

## 1.3 Up to You!
With the website I just gave you: https://www.w3schools.com/python/numpy/default.asp

I recommend working through the examples they provide (you don't have to do all of them, but a few would be good). It will help you build an intuition for numpy. It won't take very long, there are only a couple of examples per section.

Write you own **function** that follows the theme of one of the sections (i.e. array reshaping, array filter, random intro, etc). For example, if you are curious about the section "**NumPy Creating Arrays**" you could write a function that creates a multi-dimensional array.

```

>>> def make_multi_dimensional_array(one_d_array, dimensions):
...     # Creates a multi-dimensional array
...     # Your code here
...     return # Your code here

>>> my_one_d_array = [2, 4, 6, 8]
>>> my_dimension = 10
>>> ten_d_array = make_multi_dimensional_array(my_one_d_array, my_dimension)
>>> print(ten_d_array)
[[[[[[[[[[2 4 6 8]]]]]]]]]]

```

Your function should be more detailed than the example I gave you. Include at least one of the following: 
- a conditional statement
- an assignment operator
- a loop (`for` or `while`)
- `if`, `elif`, `else`, statement

In [4]:
# Your code here
import numpy as np

def make_multi_dimensional_array(oned_array, new_shape):
    # Convert the one-dimensional list to a NumPy array
    arr = np.array(oned_array)
    
    # Calculate the total number of elements
    total_elements = arr.size
    
    # Calculate the required number of elements for the new shape
    required_elements = np.prod(new_shape)
    
    # Check if the new shape is compatible with the size of the array
    if total_elements != required_elements:
        raise ValueError(f"Cannot reshape array of size {total_elements} into shape {new_shape}.")
    
    # Reshape the array into the new dimensions
    reshaped_array = arr.reshape(new_shape)
    
    return reshaped_array

# Example
my_one_d_array = [2, 4, 6, 8]
my_dimension = (2, 2)  # A shape that can fit 4 elements

ten_d_array = make_multi_dimensional_array(my_one_d_array, my_dimension)
print(ten_d_array)

[[2 4]
 [6 8]]


In the section you took inspiration from, show all of the examples below. Follow good coding practices and give at least two test cases for each example. Don't forget comments! \
\
*For my example, I took inspiration from **NumPy Creating Arrays** so I would show following examples with DIFFERENT test cases: Create a NumPy ndarray Object, Dimensions in Arrays ,0-D Arrays, 1-D Arrays, 2-D Arrays, 3-D Arrays, Check Number of Dimensions, Higher Dimensional Arrays.*

In [8]:
# Your code here
import numpy as np

# Creating a NumPy ndarray Object
def create_ndarray():
    # This function creates a NumPy array from a list
    array_1 = np.array([1, 2, 3, 4])
    array_2 = np.array([[1, 2], [3, 4]])
    
    return array_1, array_2

# 2 Test cases
array_1, array_2 = create_ndarray()
print("Array 1:", array_1)  # Expected output: [1 2 3 4]
print("Array 2:\n", array_2)  # Expected output: [[1 2] [3 4]]


# Dimensions in Arrays
def array_dimensions():
    # This function creates arrays of different dimensions
    array_1d = np.array([1, 2, 3])
    array_2d = np.array([[1, 2], [3, 4]])
    array_3d = np.array([[[1], [2]], [[3], [4]]])
    
    return array_1d.ndim, array_2d.ndim, array_3d.ndim

# Test cases
dims = array_dimensions()
print("Dimensions of 1D array:", dims[0])  # Expected output: 1
print("Dimensions of 2D array:", dims[1])  # Expected output: 2
print("Dimensions of 3D array:", dims[2])  # Expected output: 3


# Creating 0-D Arrays
def create_0d_array():
    # Creating a scalar 0-D array
    scalar_array = np.array(42)
    return scalar_array

# Test cases
scalar = create_0d_array()
print("0-D Array (Scalar):", scalar)  # Expected output: 42


# Creating 1-D Arrays
def create_1d_array():
    # Creating a 1-D array with different elements
    array_1d_1 = np.array([1, 2, 3])
    array_1d_2 = np.array([5, 10, 15, 20])
    
    return array_1d_1, array_1d_2

# 2 Test cases
array_1d_1, array_1d_2 = create_1d_array()
print("1-D Array 1:", array_1d_1)  # Expected output: [1 2 3]
print("1-D Array 2:", array_1d_2)  # Expected output: [ 5 10 15 20]


# Creating 2-D Arrays
def create_2d_array():
    # Creating a 2-D array
    array_2d_1 = np.array([[1, 2], [3, 4]])
    array_2d_2 = np.array([[5, 6, 7], [8, 9, 10]])
    
    return array_2d_1, array_2d_2

# 2 Test cases
array_2d_1, array_2d_2 = create_2d_array()
print("2-D Array 1:\n", array_2d_1)  # Expected output: [[1 2] [3 4]]
print("2-D Array 2:\n", array_2d_2)  # Expected output: [[ 5  6  7] [ 8  9 10]]


# Creating 3-D Arrays
def create_3d_array():
    # Creating a 3-D array
    array_3d_1 = np.array([[[1], [2]], [[3], [4]]])
    array_3d_2 = np.array([[[5, 6], [7, 8]], [[9, 10], [11, 12]]])
    
    return array_3d_1, array_3d_2

# 2 Test cases
array_3d_1, array_3d_2 = create_3d_array()
print("3-D Array 1:\n", array_3d_1)  # Expected output: [[[1] [2]] [[3] [4]]]
print("3-D Array 2:\n", array_3d_2)  # Expected output: [[[ 5  6] [ 7  8]] [[ 9 10] [11 12]]]


# Check the Number of Dimensions
def check_number_of_dimensions(array):
    # Check and return the number of dimensions of the given array
    return array.ndim

# 2 Test cases
array_1d = np.array([1, 2, 3])
array_2d = np.array([[1, 2], [3, 4]])
print("Number of dimensions of array_1d:", check_number_of_dimensions(array_1d))  # Expected output: 1
print("Number of dimensions of array_2d:", check_number_of_dimensions(array_2d))  # Expected output: 2


# Create Higher Dimensional Arrays
def create_higher_dimensional_array():
    # Creating a higher dimensional array (4-D)
    array_4d = np.random.rand(2, 3, 4, 5)  # Random values in a 4-D array
    return array

Array 1: [1 2 3 4]
Array 2:
 [[1 2]
 [3 4]]
Dimensions of 1D array: 1
Dimensions of 2D array: 2
Dimensions of 3D array: 3
0-D Array (Scalar): 42
1-D Array 1: [1 2 3]
1-D Array 2: [ 5 10 15 20]
2-D Array 1:
 [[1 2]
 [3 4]]
2-D Array 2:
 [[ 5  6  7]
 [ 8  9 10]]
3-D Array 1:
 [[[1]
  [2]]

 [[3]
  [4]]]
3-D Array 2:
 [[[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Number of dimensions of array_1d: 1
Number of dimensions of array_2d: 2


In 2-3 sentences, describe how your function took inspiration from a section.\
\
*For my example, `make_multi_dimensional_array`, I would talk about the **NumPy Creating Arrays** section and how I took inspiration from the example **Higher Dimensional Arrays**.*

In [6]:
# Your comment here
# My function was inspired by the "NumPy Reshaping Arrays" section, which shows like the importance of transforming arrays into arrays of different dimensions.
# My funcion does this while still ensuring that the array works with the original data size if that makes sense. 
# My fuction also incorporates like an error measurement to check if the total number of elements matches the product of the new shape. 
# It also demonstrates the use of NumPy’s reshaping capabilities in a really clear coherent way, hopefully lol.

# 2 Brianna's Module
During lecture we created and worked with a module called `even_sum.py`. Import that module here. 

In [35]:
# Your code here
import even_sum

Now that you have imported the module. Call the module and the first function with your own list of numbers. 

In [39]:
# Your code here
my_list = (11, 24, 56, 34, 45, 57, 87, 52)

even_sum.sum_even_numbers(my_list)

166

I have provided you a separate module called `example.py`. Import that module here.

In [36]:
# Your code here
import example

With the following variables, use my module to show which of the rocket's escape!

In [37]:
rocket_velocities = np.array([
    [1000, 5000, 8000, 12000],  # Rocket 1's velocity at different times
    [2000, 6000, 9000, 10000],  # Rocket 2
    [3000, 3100, 3200, 3300]    # Rocket 3
])

mass_of_planet = 5.972e24 # kilograms
radius_of_planet = 6.371e6 # meters

In [45]:
# Your code here
example.rocket_launch(rocket_velocities, mass_of_planet, radius_of_planet)
# This function will return wether or not a rocket makes it out of a planets gravitational pull based on the rocket velocity, planet mass and planet radius.

['Rocket left the planet!',
 'Rocket is orbiting around the planet.',
 'Rocket crashes back into the planet!']

In 2-3 sentences describe how this code follows "good coding practices" and where there is room for improvement.

In [44]:
# Your comments here
# I mean, I did what we did in class to return the function, however there's not much discription in the function itself and explaining what it does.
# There is a comment that explains what the function returns which is good coding practice.
# The variables are all well defined and their "meanings" are very clear!

# 3 Your Turn!
Now its your turn to make a module! Choose a topic from a class (could be physics, computer science, nuclear engineering, biology, astronomy, math, or an topic that interests you!) and build a module around it! Look at my module called `example.py` and base your structure around it. Your module NEEDS to include the following.

Overall:
1) Your module needs to use at least one NumPy function: https://numpy.org/devdocs/reference/routines.math.html
2) Your module needs to contain a multi-dimensional array: https://numpy.org/devdocs/reference/arrays.ndarray.html 
3) Your module needs **at least** three functions that follow good coding practices.
4) Inside your function, include comments. Don't forget to describe what the function is doing and what the inputs and outputs are.
5) Your module needs either a `for` loop or `while` loop.
6) Your module needs an `if`, `elif`, and `else` statement.
7) Your module needs at least two assignment variables (`+=`, `*=`, etc).
8) Creativity. *If it looks like you plugged this whole thing into ChatGPT, I will take off points. You can use ChatGPT to help you code, but you can't use it to just do your homework for you. That's no fun :(*

In 2-3 sentences, describe the topic of your module and its capabilities. 

In [ ]:
# Your comment here
# My function is designed to calculate the amount of material erupted using the height an radius of the eruption column.
# It is then used to classify the eruption based on the VEI (volcanic ecplosivity index)
# It uses conditional statements to categorize eruptions on a scale from non-explosive to very large.
# Then, it analyzes the eruption and classifies them
# Yay! I love volcanology!

In 2-3 sentences, answer the following. What was the most challenging part of building this module? What did you learn in the process that you can apply to future coding assignments?

In [1]:
# Your comment here
# The most challenging part of building the module was ensuring it met all the specified requirements while maintaining clarity and efficiency. 
# I learned the importance of structuring code with clear comments and integrating powerful libraries like NumPy to handle complex calculations.
# Also, realistically I actually get so frustrated when my coding does work so im pretty sure it took my like 3 hours and way to much caffeine to do this.
# All of the essential "good coding skills" I added are really important for any and all future coding projects.

Once your module is complete, import it here.

In [46]:
# Your code here
import volcano_analysis

Call each of your functions in the cell below. Make sure to show the outputs! 

In [2]:
# Your code here
import volcano_analysis
import numpy as np

# Example call to analyze_eruptions
eruption_data = np.array([
    [1000, 300, 5],
    [500, 150, 3],
    [200, 50, 1]
])

eruptions = [{'height': row[0], 'radius': row[1], 'vei': row[2]} for row in eruption_data]
analysis_results = volcano_analysis.analyze_eruptions(eruptions)

for i, (volume, classification) in enumerate(analysis_results):
    print(f"Eruption {i + 1}: Volume = {volume:.2f} cubic meters, Classification = {classification}")

Eruption 1: Volume = 94247779.61 cubic meters, Classification = Large
Eruption 2: Volume = 11780972.45 cubic meters, Classification = Moderate
Eruption 3: Volume = 523598.78 cubic meters, Classification = Small


# 4 Proper Submission
To recieve full credit for this assignment make sure you do the following:

1) Copy this homework assignment from the `ulab_2024` repository into **YOUR** local `homework7` branch. It will contain this notebook and an additional file called `example.py`. 
   
2) Follow the tasks. Make sure to run all the cells so that **all** output is visible. You will get points taken off if your ouputs are not shown!

3) Add/commit/push this notebook and **ANY** modules (so you should have `example.py` and your module) used in this homework assignment to your remote `homework7` branch. Make sure to have NOTHING else in your branch (i.e. no previous homeworks or lecture notes).

4) Do the following:
- Take a screenshot of moving **into or out** of your `homework7` brach, call it `hw7_branch`.
- Take a screenshot of calling `ls` in your `homework7` branch, it should only contain items relevent to homework 7, call it `hw7_ls`.
- Take a screenshot of adding this assignment to your local `homework7` branch, call it `hw7_add`.
- Take a screenshot of committing this assignment to your local `homework7` branch, call it `hw7_commit`.
- Take a screenshot of pushing this assignment to your remote `homework7` branch, call it `hw7_push`. 

6) Include these screenshots in your `homework7` branch. Upload your `homework7` branch to Gradescope!